### ISSUE TITLE
Use shizuku for ADB-like actions

### ISSUE THREAD

**Issue by thomassth** [mirfatif/PermissionManagerX#24] opened 2022-02-10 13:04 UTC
There's an app called Shizuku that allows extended access to system. 

It can also be done without connecting to PC. 

It would be easier for non-root users with this. They also seems to have an API ready.
https://github.com/RikkaApps/Shizuku

**Comment by mirfatif** [comment] 2022-02-10 13:10
Due to design limitations, we are unable to use Shizuku API. See this [FAQ](https://mirfatif.github.io/PermissionManagerX/help/help#faq30).

> It can also be done without connecting to PC.

It's already supported. See [this](https://mirfatif.github.io/PermissionManagerX/help/help#adb_help_11).
We are going to further improve it (like [here](https://mirfatif.github.io/WhatsRunning/help/help#adb-help-11)) to eliminate the need of Termux.

**Comment by mirfatif** [comment] 2022-02-10 13:14
Duplicate of https://github.com/mirfatif/PermissionManagerX/issues/13

**Closed as completed** 2022-02-11 11:14 UTC
