### ISSUE TITLE
backup/restore question

### ISSUE THREAD

**Issue by Roki100** [mirfatif/PermissionManagerX#35] opened 2023-06-06 00:55 UTC
hi, i wanted to restore app perms from my prev phone but it seems it doesnt touch notification perms? android blocks them by default and i need a tool to recover apps i had notifs allowed for... because theres over 200

**Comment by mirfatif** [comment] 2023-06-06 23:43
Sorry I'm not clear what you are asking.

What are "notification perms" exactly? Were they backed up on your previous phone?

> Android blocks them by default

Does it relate to PMX backup / restore?

**Comment by Roki100** [comment] 2023-06-07 00:41
android since a while defaults to blocking notification permissions for apps, i used your app to back up my previous phone and restore them on the new one but it doesnt seem to affect the permissions for sending notifications

**Comment by mirfatif** [comment] 2023-06-07 08:10
I assume you are a talking about `android.permission.POST_NOTIFICATIONS`.

Please note that restoring a backup only restores the [Permission References](https://mirfatif.github.io/PermissionManagerX/help/en/#perm_ref). It does not set the permission states.

There is an upcoming feature named **Permission Profiles** which you'll be able to use for batch operations on permissions and permission references.

**Comment by Roki100** [comment] 2023-06-08 01:33
yeah thats excatly what i was having on my mind, sounds good it is an upcoming feature then, thanks!

**Comment by mirfatif** [comment] 2023-07-02 08:20
Duplicate of 27

**Comment by mirfatif** [comment] 2023-07-02 08:20
Duplicate of https://github.com/mirfatif/PermissionManagerX/issues/27

**Closed by mirfatif** 2023-07-02 08:20 UTC
