### ISSUE TITLE
Authorized use with other applications

### ISSUE THREAD

**Issue by TingTing1990** [mirfatif/PermissionManagerX#32] opened 2022-12-11 00:29 UTC
Hi, is PMX able to be used with Shizuku authorization to get adb access?

https://shizuku.rikka.app/

**Comment by TingTing1990** [comment] 2022-12-11 01:16
Thank you!

**Comment by mirfatif** [comment] 2022-12-11 01:56
Duplicate of https://github.com/mirfatif/PermissionManagerX/issues/24

**Closed** 2022-12-11 01:57 UTC
